apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-backstage
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/your-org/idp-platform.git
    targetRevision: main
    path: kubernetes/backstage
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
