apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-keycloak
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: git@github.com:ZakariaAitAli/idp-platform.git
    targetRevision: main
    path: kubernetes/keycloak
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
