apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-vault
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/ZakariaAitAli/idp-platform.git
    targetRevision: main
    path: kubernetes/vault
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
