apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-local-metallb
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: git@github.com:ZakariaAitAli/idp-platform.git
    targetRevision: main
    path: kubernetes/metallb/local
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
