apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-app
  namespace: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: example-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/data/dev/example-app/credentials
        property: password
