apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-root
  namespace: argocd
  labels:
    platform/role: bootstrap
spec:
  project: default
  source:
    repoURL: https://github.com/ZakariaAitAli/idp-platform.git
    targetRevision: main
    path: gitops/root
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
