apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ZakariaAitAli/idp-platform.git
    targetRevision: main
    path: kubernetes/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
